language: scala
scala:
  - 2.10.5
python:
  - "2.7"
jdk:
  - oraclejdk7 # openJDK crashes sometimes
sudo: false
cache:
  directories:
    - $HOME/.ivy2
    - $HOME/.cache/spark-versions
env:
  matrix:
    - SPARK_VERSION=1.6.0 SPARK_BUILD="spark-1.6.0-bin-hadoop2.6" SPARK_BUILD_URL="http://d3kbcqa49mib13.cloudfront.net/spark-1.6.0-bin-hadoop2.6.tgz"
    - SPARK_VERSION=1.5.2 SPARK_BUILD="spark-1.5.2-bin-hadoop2.6" SPARK_BUILD_URL="http://d3kbcqa49mib13.cloudfront.net/spark-1.5.2-bin-hadoop2.6.tgz"
    - SPARK_VERSION=1.4.1 SPARK_BUILD="spark-1.4.1-bin-hadoop2.6" SPARK_BUILD_URL="http://d3kbcqa49mib13.cloudfront.net/spark-1.4.1-bin-hadoop2.6.tgz"

before_install:
 - ./bin/download_travis_dependencies.sh

install: 
 - pip install --user -r ./python/requirements.txt

script:
  - SPARK_HOME=$HOME/.cache/spark-versions/$SPARK_BUILD ./python/run-tests.sh